logging:
  config: classpath:log4j2-local.xml

livereload.sources: src/main/resources/static/,src/main/resources/templates/

spring:
  devtools:
    livereload:
      enabled: 'true'
  thymeleaf:
    cache: 'false'
    prefix: file:src/main/resources/templates/  # trailing '/' is mandatory
    check-template-location: 'true'

  web:
    resources:
      static-locations:
        - file:src/main/resources/static/
        - classpath:/static/
      cache:
        period: 0