server.port: 9090
spring:
  application.name: reports
  datasource:
    url: ${DB_URL}
    username: ${DB_UID}
    password: ${DB_PWD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    static-path-pattern: /resources/**

