server:
  port: 9090
  error:
    path: /error
    whitelabel:
      enabled: false
spring:
  application.name: reports

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
#  mvc:
#    static-path-pattern: /resources/**
