INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('AF', 'Afghanistan', 'The Islamic Republic of Afghanistan', 'Afghan');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('AL', 'Albania', 'The Republic of Albania', 'Albanian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('DZ', 'Algeria', 'The People''s Democratic Republic of Algeria', 'Algerian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('AD', 'Andorra', 'The Principality of Andorra', 'Andorran');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('AO', 'Angola', 'The Republic of Angola', 'Angolan');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('AG', 'Antigua and Barbuda', 'Antigua and Barbuda', 'Citizen of Antigua and Barbuda');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('AR', 'Argentina', 'The Argentine Republic', 'Argentine');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('AM', 'Armenia', 'The Republic of Armenia', 'Armenian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('AU', 'Australia', 'The Commonwealth of Australia', 'Australian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('AT', 'Austria', 'The Republic of Austria', 'Austrian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('AZ', 'Azerbaijan', 'The Republic of Azerbaijan', 'Azerbaijani');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('BH', 'Bahrain', 'The Kingdom of Bahrain', 'Bahraini');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('BD', 'Bangladesh', 'The People''s Republic of Bangladesh', 'Bangladeshi');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('BB', 'Barbados', 'Barbados', 'Barbadian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('BY', 'Belarus', 'The Republic of Belarus', 'Belarusian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('BE', 'Belgium', 'The Kingdom of Belgium', 'Belgian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('BZ', 'Belize', 'Belize', 'Belizean');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('BJ', 'Benin', 'The Republic of Benin', 'Beninese');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('BT', 'Bhutan', 'The Kingdom of Bhutan', 'Bhutanese');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('BO', 'Bolivia', 'The Plurinational State of Bolivia', 'Bolivian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('BA', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'Citizen of Bosnia and Herzegovina');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('BW', 'Botswana', 'The Republic of Botswana', 'Botswanan');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('BR', 'Brazil', 'The Federative Republic of Brazil', 'Brazilian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('BN', 'Brunei', 'Brunei Darussalam', 'Bruneian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('BG', 'Bulgaria', 'The Republic of Bulgaria', 'Bulgarian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('BF', 'Burkina Faso', 'Burkina Faso', 'Burkinan');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('BI', 'Burundi', 'The Republic of Burundi', 'Burundian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('KH', 'Cambodia', 'The Kingdom of Cambodia', 'Cambodian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('CM', 'Cameroon', 'The Republic of Cameroon', 'Cameroonian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('CA', 'Canada', 'Canada', 'Canadian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('CV', 'Cape Verde', 'The Republic of Cabo Verde', 'Cape Verdean');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('CF', 'Central African Republic', 'The Central African Republic', 'Central African');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('TD', 'Chad', 'The Republic of Chad', 'Chadian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('CL', 'Chile', 'The Republic of Chile', 'Chilean');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('CN', 'China', 'The People''s Republic of China', 'Chinese');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('CO', 'Colombia', 'The Republic of Colombia', 'Colombian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('KM', 'Comoros', 'The Union of the Comoros', 'Comoran');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('CG', 'Congo', 'The Republic of the Congo', 'Congolese (Republic of the Congo)');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('CD', 'Congo (Democratic Republic)', 'The Democratic Republic of the Congo', 'Congolese (DRC)');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('CR', 'Costa Rica', 'The Republic of Costa Rica', 'Costa Rican');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('HR', 'Croatia', 'The Republic of Croatia', 'Croatian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('CU', 'Cuba', 'The Republic of Cuba', 'Cuban');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('CY', 'Cyprus', 'The Republic of Cyprus', 'Cypriot');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('CZ', 'Czechia', 'The Czech Republic', 'Czech');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('DK', 'Denmark', 'The Kingdom of Denmark', 'Danish');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('DJ', 'Djibouti', 'The Republic of Djibouti', 'Djiboutian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('DM', 'Dominica', 'The Commonwealth of Dominica', 'Dominican');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('DO', 'Dominican Republic', 'The Dominican Republic', 'Citizen of the Dominican Republic');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('TL', 'East Timor', 'The Democratic Republic of Timor-Leste', 'East Timorese');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('EC', 'Ecuador', 'The Republic of Ecuador', 'Ecuadorean');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('EG', 'Egypt', 'The Arab Republic of Egypt', 'Egyptian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('SV', 'El Salvador', 'The Republic of El Salvador', 'Salvadorean');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('GQ', 'Equatorial Guinea', 'The Republic of Equatorial Guinea', 'Equatorial Guinean');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('ER', 'Eritrea', 'The State of Eritrea', 'Eritrean');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('EE', 'Estonia', 'The Republic of Estonia', 'Estonian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('SZ', 'Eswatini', 'Kingdom of Eswatini', 'Swazi');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('ET', 'Ethiopia', 'The Federal Democratic Republic of Ethiopia', 'Ethiopian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('FJ', 'Fiji', 'The Republic of Fiji', 'Fijian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('FI', 'Finland', 'The Republic of Finland', 'Finnish');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('FR', 'France', 'The French Republic', 'French');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('GA', 'Gabon', 'The Gabonese Republic', 'Gabonese');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('GE', 'Georgia', 'Georgia', 'Georgian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('DE', 'Germany', 'The Federal Republic of Germany', 'German');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('GH', 'Ghana', 'The Republic of Ghana', 'Ghanaian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('GR', 'Greece', 'The Hellenic Republic', 'Greek');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('GD', 'Grenada', 'Grenada', 'Grenadian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('GT', 'Guatemala', 'The Republic of Guatemala', 'Guatemalan');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('GN', 'Guinea', 'The Republic of Guinea', 'Guinean');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('GW', 'Guinea-Bissau', 'The Republic of Guinea-Bissau', 'Citizen of Guinea-Bissau');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('GY', 'Guyana', 'The Co-operative Republic of Guyana', 'Guyanese');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('HT', 'Haiti', 'The Republic of Haiti', 'Haitian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('HN', 'Honduras', 'The Republic of Honduras', 'Honduran');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('HU', 'Hungary', 'Hungary', 'Hungarian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('IS', 'Iceland', 'Iceland', 'Icelandic');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('IN', 'India', 'The Republic of India', 'Indian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('ID', 'Indonesia', 'The Republic of Indonesia', 'Indonesian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('IR', 'Iran', 'The Islamic Republic of Iran', 'Iranian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('IQ', 'Iraq', 'The Republic of Iraq', 'Iraqi');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('IE', 'Ireland', 'Ireland', 'Irish');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('IL', 'Israel', 'The State of Israel', 'Israeli');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('IT', 'Italy', 'The Italian Republic', 'Italian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('CI', 'Ivory Coast', 'The Republic of C�te D�Ivoire', 'Ivorian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('JM', 'Jamaica', 'Jamaica', 'Jamaican');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('JP', 'Japan', 'Japan', 'Japanese');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('JO', 'Jordan', 'The Hashemite Kingdom of Jordan', 'Jordanian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('KZ', 'Kazakhstan', 'The Republic of Kazakhstan', 'Kazakh');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('KE', 'Kenya', 'The Republic of Kenya', 'Kenyan');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('KI', 'Kiribati', 'The Republic of Kiribati', 'Citizen of Kiribati');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('XK', 'Kosovo', 'The Republic of Kosovo', 'Kosovan');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('KW', 'Kuwait', 'The State of Kuwait', 'Kuwaiti');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('KG', 'Kyrgyzstan', 'The Kyrgyz Republic', 'Kyrgyz');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('LA', 'Laos', 'The Lao People''s Democratic Republic', 'Lao');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('LV', 'Latvia', 'The Republic of Latvia', 'Latvian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('LB', 'Lebanon', 'The Lebanese Republic', 'Lebanese');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('LS', 'Lesotho', 'The Kingdom of Lesotho', 'Citizen of Lesotho');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('LR', 'Liberia', 'The Republic of Liberia', 'Liberian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('LY', 'Libya', 'State of Libya', 'Libyan');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('LI', 'Liechtenstein', 'The Principality of Liechtenstein', 'Liechtenstein citizen');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('LT', 'Lithuania', 'The Republic of Lithuania', 'Lithuanian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('LU', 'Luxembourg', 'The Grand Duchy of Luxembourg', 'Luxembourger');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('MG', 'Madagascar', 'The Republic of Madagascar', 'Citizen of Madagascar');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('MW', 'Malawi', 'The Republic of Malawi', 'Malawian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('MY', 'Malaysia', 'Malaysia', 'Malaysian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('MV', 'Maldives', 'The Republic of Maldives', 'Maldivian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('ML', 'Mali', 'The Republic of Mali', 'Malian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('MT', 'Malta', 'The Republic of Malta', 'Maltese');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('MH', 'Marshall Islands', 'The Republic of the Marshall Islands', 'Marshallese');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('MR', 'Mauritania', 'The Islamic Republic of Mauritania', 'Mauritanian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('MU', 'Mauritius', 'The Republic of Mauritius', 'Mauritian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('MX', 'Mexico', 'The United Mexican States', 'Mexican');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('FM', 'Federated States of Micronesia', 'Federated States of Micronesia', 'Micronesian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('MD', 'Moldova', 'The Republic of Moldova', 'Moldovan');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('MC', 'Monaco', 'The Principality of Monaco', 'Monegasque');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('MN', 'Mongolia', 'Mongolia', 'Mongolian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('ME', 'Montenegro', 'Montenegro', 'Montenegrin');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('MA', 'Morocco', 'The Kingdom of Morocco', 'Moroccan');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('MZ', 'Mozambique', 'The Republic of Mozambique', 'Mozambican');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('MM', 'Myanmar (Burma)', 'The Republic of the Union of Myanmar', 'Citizen of Myanmar');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('NA', 'Namibia', 'The Republic of Namibia', 'Namibian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('NR', 'Nauru', 'The Republic of Nauru', 'Nauruan');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('NP', 'Nepal', 'Nepal', 'Nepalese');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('NL', 'Netherlands', 'The Kingdom of the Netherlands', 'Dutch');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('NZ', 'New Zealand', 'New Zealand', 'New Zealander');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('NI', 'Nicaragua', 'The Republic of Nicaragua', 'Nicaraguan');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('NE', 'Niger', 'The Republic of Niger', 'Nigerien');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('NG', 'Nigeria', 'The Federal Republic of Nigeria', 'Nigerian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('KP', 'North Korea', 'The Democratic People''s Republic of Korea', 'North Korean');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('MK', 'North Macedonia', 'Republic of North Macedonia', 'Macedonian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('NO', 'Norway', 'The Kingdom of Norway', 'Norwegian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('OM', 'Oman', 'The Sultanate of Oman', 'Omani');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('PK', 'Pakistan', 'The Islamic Republic of Pakistan', 'Pakistani');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('PW', 'Palau', 'The Republic of Palau', 'Palauan');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('PA', 'Panama', 'The Republic of Panama', 'Panamanian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('PG', 'Papua New Guinea', 'The Independent State of Papua New Guinea', 'Papua New Guinean');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('PY', 'Paraguay', 'The Republic of Paraguay', 'Paraguayan');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('PE', 'Peru', 'The Republic of Peru', 'Peruvian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('PH', 'Philippines', 'The Republic of the Philippines', 'Filipino');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('PL', 'Poland', 'The Republic of Poland', 'Polish');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('PT', 'Portugal', 'The Portuguese Republic', 'Portuguese');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('QA', 'Qatar', 'The State of Qatar', 'Qatari');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('RO', 'Romania', 'Romania', 'Romanian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('RU', 'Russia', 'The Russian Federation', 'Russian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('RW', 'Rwanda', 'The Republic of Rwanda', 'Rwandan');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('KN', 'St Kitts and Nevis', 'The Federation of Saint Christopher and Nevis', 'Citizen of St Christopher (St Kitts) and Nevis');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('LC', 'St Lucia', 'Saint Lucia', 'St Lucian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('VC', 'St Vincent', 'Saint Vincent and the Grenadines', 'Vincentian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('WS', 'Samoa', 'The Independent State of Samoa', 'Samoan');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('SM', 'San Marino', 'The Republic of San Marino', 'San Marinese');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('ST', 'Sao Tome and Principe', 'The Democratic Republic of Sao Tome and Principe', 'Sao Tomean');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('SA', 'Saudi Arabia', 'The Kingdom of Saudi Arabia', 'Saudi Arabian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('SN', 'Senegal', 'The Republic of Senegal', 'Senegalese');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('RS', 'Serbia', 'The Republic of Serbia', 'Serbian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('SC', 'Seychelles', 'The Republic of Seychelles', 'Citizen of Seychelles');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('SL', 'Sierra Leone', 'The Republic of Sierra Leone', 'Sierra Leonean');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('SG', 'Singapore', 'The Republic of Singapore', 'Singaporean');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('SK', 'Slovakia', 'The Slovak Republic', 'Slovak');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('SI', 'Slovenia', 'The Republic of Slovenia', 'Slovenian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('SB', 'Solomon Islands', 'Solomon Islands', 'Solomon Islander');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('SO', 'Somalia', 'Federal Republic of Somalia', 'Somali');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('ZA', 'South Africa', 'The Republic of South Africa', 'South African');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('KR', 'South Korea', 'The Republic of Korea', 'South Korean');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('SS', 'South Sudan', 'The Republic of South Sudan', 'South Sudanese');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('ES', 'Spain', 'The Kingdom of Spain', 'Spanish');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('LK', 'Sri Lanka', 'The Democratic Socialist Republic of Sri Lanka', 'Sri Lankan');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('SD', 'Sudan', 'The Republic of the Sudan', 'Sudanese');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('SR', 'Suriname', 'The Republic of Suriname', 'Surinamese');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('SE', 'Sweden', 'The Kingdom of Sweden', 'Swedish');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('CH', 'Switzerland', 'The Swiss Confederation', 'Swiss');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('SY', 'Syria', 'The Syrian Arab Republic', 'Syrian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('TJ', 'Tajikistan', 'The Republic of Tajikistan', 'Tajik');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('TZ', 'Tanzania', 'The United Republic of Tanzania', 'Tanzanian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('TH', 'Thailand', 'The Kingdom of Thailand', 'Thai');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('BS', 'The Bahamas', 'The Commonwealth of The Bahamas', 'Bahamian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('GM', 'The Gambia', 'The Republic of The Gambia', 'Gambian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('TG', 'Togo', 'The Togolese Republic', 'Togolese');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('TO', 'Tonga', 'The Kingdom of Tonga', 'Tongan');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('TT', 'Trinidad and Tobago', 'The Republic of Trinidad and Tobago', 'Trinidad and Tobago citizen');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('TN', 'Tunisia', 'Republic of Tunisia', 'Tunisian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('TR', 'Turkey', 'Republic of T�rkiye', 'Turk, Turkish');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('TM', 'Turkmenistan', 'Turkmenistan', 'Turkmen');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('TV', 'Tuvalu', 'Tuvalu', 'Tuvaluan');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('UG', 'Uganda', 'The Republic of Uganda', 'Ugandan');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('UA', 'Ukraine', 'Ukraine', 'Ukrainian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('AE', 'United Arab Emirates', 'The United Arab Emirates', 'Citizen of the United Arab Emirates');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('GB', 'United Kingdom', 'The United Kingdom of Great Britain and Northern Ireland', 'Briton, British');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('US', 'United States', 'The United States of America', 'American');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('UY', 'Uruguay', 'The Oriental Republic of Uruguay', 'Uruguayan');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('UZ', 'Uzbekistan', 'The Republic of Uzbekistan', 'Uzbek');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('VU', 'Vanuatu', 'The Republic of Vanuatu', 'Citizen of Vanuatu');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('VA', 'Vatican City', 'Vatican City State', 'Vatican citizen');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('VE', 'Venezuela', 'The Bolivarian Republic of Venezuela', 'Venezuelan');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('VN', 'Vietnam', 'The Socialist Republic of Viet Nam', 'Vietnamese');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('YE', 'Yemen', 'The Republic of Yemen', 'Yemeni');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('ZM', 'Zambia', 'The Republic of Zambia', 'Zambian');
INSERT INTO countries (country_code, name, official_name, citizen_name) VALUES ('ZW', 'Zimbabwe', 'The Republic of Zimbabwe', 'Zimbabwean');





